from typing import Protocol, Sequence
from .schemas import HotelRecord
class HotelExtractor(Protocol):
    def extract(self, text: str, source_pages: list[int]) -> HotelRecord: ...
class EmbeddingProvider(Protocol):
    def embed(self, texts: Sequence[str]) -> list[list[float]]: ...
class HotelRepository(Protocol):
    def upsert(self, records: Sequence[HotelRecord]) -> int: ...
    def search(self, query: str, limit: int) -> list[dict]: ...
